### ISSUE TITLE
Trimmer: The term 'False' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by skest3qc** [guyrleech/Microsoft#1]
Hi, 
first, thanks for this script.
I have tried it now and get the following error when I run Trim idle task:
`
False : The term 'False' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ False
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (False:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
False : The term 'False' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ False
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (False:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException
`
Task is calling this:
`powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\TEMP\Trimmer.ps1 -ThisSession -scheduled -Idle 600 -background -above 10485760 -available False -logfile C:\TEMP\MemoryOptimization.log -processes firefox,iexplore`

```
Transscript:
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT TotalPhysicalMemory FROM Win32_ComputerSystem,'queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Available memory is 5797MB out of 8191MB total (71%)
False : The term 'False' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ False
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (False:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
False : The term 'False' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ False
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (False:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

VERBOSE: Not trimming as memory available is above specified threshold
```

**Comment by guyrleech** [comment]
Not sure how that was actually happening sorry but I could reproduce and have put a workaround in place.

You will have to remove your existing scheduled tasks with -uninstall and then install again.

Thanks for the feedback.
