### ISSUE TITLE
Trimmer: Parameter -Processes seems to do nothing

### ISSUE THREAD

**Issue by skest3qc** [guyrleech/Microsoft#2]
Using -Processes firefox,iexplore seems to do not optimize Memory for these processes.
If I remove the Processes parameter it works well. 

`powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\TEMP\Trimmer.ps1 -ThisSession -scheduled -above 10485760 -logfile C:\TEMP\MemoryOptimization.log -Processes "firefox","iexplore" -Verbose`

Verbose Logging:
```
VERBOSE: 	Skipping firefox pid 7868 as not specified process
VERBOSE: 	Skipping iexplore pid 2128 as not specified process
VERBOSE: 	Skipping iexplore pid 4528 as not specified process
VERBOSE: 	Skipping iexplore pid 8540 as not specified process
VERBOSE: 	Skipping iexplore pid 8608 as not specified process
```

It seems that you are trying to compare to $process.Name but it should be $process.ProcessName and if you put this $processes = $processes.Split(",") before Get-Process routine it works.

To speed up Get-Process I would supply $processes with parameter Name if processes are present, it should be faster...

**Comment by guyrleech** [comment]
Thanks for using and feeding back - it is much appreciated.

This is because when the script is invoked external to an existing PowerShell session, array parameters get passed as a single string. I have put code in to workaround this.

See carlwebster.com/running-powershell-scheduled-tasks-second-opinion/ for more detail

**Comment by skest3qc** [comment]
Hi,

thanks it works now, could you put this also in:

To speed up Get-Process I would supply Get-Process -Name $processes (if provided), it is much faster and uses less CPU.

Thanks

**Comment by guyrleech** [comment]
Thanks again for the feedback. I was going to implement regexs for the
process names but you're quite right, it is quicker to filter in
Get-Process so I've done that and also done it for the process id option
although that's unlikely to be used.

I've also added -includeUsers and -excludeUsers options but the arguments
must be domain/local qualified (see script help for details)
